{% set name = "fparser" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3901d31c104062c4e532248286929e7405e43b79a6a85815146a176673e69c82

build:
  entry_points:
    - fparser2=fparser.scripts.fparser2:main
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7

test:
  imports:
    - fparser
    - fparser.common
    - fparser.common.tests
    - fparser.one
    - fparser.one.tests
    - fparser.scripts
    - fparser.two
  commands:
    - fparser2 --help

about:
  home: https://github.com/stfc/fparser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern Fortran Parser
  doc_url: https://github.com/stfc/fparser
  dev_url: https://github.com/stfc/fparser

extra:
  recipe-maintainers:
    - arporter
    - matthewrmshin
    - MatthewHambley
    - rupertford
